Feature/homework 11 2
Mary1106/homework pull request #4
Opened 2024-08-23 13:08 UTC by Mary1106

2024-08-23 13:48 UTC, painassasin requested changes

2024-08-23 13:48 UTC, painassasin commented on .flake8
> +ignore = F541
Нужно удалить игнор и исправить ошибку, на которую ругается flake

2024-08-23 13:48 UTC, painassasin commented on src/decorators.py
> +def log(filename: str | None) -> Callable:
Нужно указать дефолтное значение None

2024-08-23 13:48 UTC, painassasin commented on src/decorators.py
> +def my_function(x: int, y: int) -> int:
Исполняемый код нужно удалить из модуля - в decorators.py должен остаться только декоратор (и импорты для него)

2024-08-23 13:48 UTC, painassasin commented on tests/test_decorators.py
> +def test_log_error(capsys):
Что проверяет этот тест?

2024-08-23 13:48 UTC, painassasin commented on tests/test_decorators.py
> +    with pytest.raises(Exception):
Что проверяет этот тест?

2024-08-24 07:28 UTC, Mary1106 commented on .flake8
> +ignore = F541
сделано

2024-08-24 07:28 UTC, Mary1106 commented on src/decorators.py
> +def log(filename: str | None) -> Callable:
кажется, сделано)

2024-08-24 07:29 UTC, Mary1106 commented on src/decorators.py
> +def my_function(x: int, y: int) -> int:
убрала лишнее

2024-08-24 16:02 UTC, painassasin requested changes

2024-08-24 16:02 UTC, painassasin commented on src/decorators.py
> +def log(filename: str = None) -> Callable:
Раз у тебя дефолтно None, то и тип может быть строка или None
```
filename: str | None = None
```

2024-08-24 16:10 UTC, painassasin requested changes

2024-08-24 16:10 UTC, painassasin commented on src/decorators.py
> +                log_message = f"my_function is not ok: {error}. Inputs:{args}, {kwargs}"
Должно логировать название функции, которую декорируешь, а не `my_function`

2024-08-24 16:11 UTC, painassasin requested changes

2024-08-24 16:11 UTC, painassasin commented on src/decorators.py
> +            return
Должен возвращаться результат функции, а не None

2024-08-24 16:14 UTC, painassasin requested changes

2024-08-24 16:14 UTC, painassasin commented on src/decorators.py
> +            if filename is not None:
Лучше это вынести в отдельную функцию, а в декораторе просто вызвать ее (расположить на уровне wrapper)
```python
 def _log_result(message: str) -> None:
        if filename is not None:
            with open(filename, "a", encoding="utf-8") as file:
                file.write(f"{message}\n")
        else:
            print(None)
 ```

2024-08-24 16:15 UTC, painassasin commented on src/decorators.py
> +            return
Причем если возникло исключение - его нужно рейзить наружу

2024-08-28 15:51 UTC, painassasin requested changes

2024-08-28 15:51 UTC, painassasin commented on src/decorators.py
> +                log_message = f"{func.__name__} is not ok: {error}. Inputs:{args}, {kwargs}"
Если в функции возникает исключение - его нужно рейзить + логировать

2024-08-28 15:51 UTC, painassasin commented on src/decorators.py
> +                log_message = f"{func.__name__} is ok"
Если функция завершилась успешно - нужно возвращать результат выполнения + логировать

2024-08-28 15:51 UTC, painassasin commented on src/decorators.py
> +my_function(1, 2)
Исполняемый код нужно убрать (оставь только декоратор в этом файле)

2024-08-28 18:05 UTC, Mary1106 commented on src/decorators.py
> +                log_message = f"{func.__name__} is not ok: {error}. Inputs:{args}, {kwargs}"
Если рейзить - это про raise, то я не понимаю, как его использовать, не зная функции, которая попадет в декоратор...
Сделала подругому, вроде работает как надо

2024-08-28 18:05 UTC, Mary1106 commented on src/decorators.py
> +                log_message = f"{func.__name__} is ok"
результат добавила

2024-08-28 18:06 UTC, Mary1106 commented on src/decorators.py
> +my_function(1, 2)
убрала

2024-09-04 16:14 UTC, painassasin commented on tests/test_decorators.py
> +    @log(filename=None)
Путь до файла нужно было передать в декоратор и ее же вызвать
```python
@log(filename=log_file.strpath)
def my_function(x: int, y: int) -> int:
    return x + y

my_function(1, 2)
````

2024-09-16 10:56 UTC, merged